---
title: "Meet ggplot2 extensions"
subtitle: "Take your ggplot2 skills up a notch"
author: "<br><br>Ashirwad Barnwal&nbsp;&nbsp;&nbsp;"
date: "<br>18-Feb-2021<br><br>"
output: 
  xaringan::moon_reader:
    css: ["default", "kunoichi", "ninjutsu", "assets/custom.css"]
    nature:
      ratio: "16:9"
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
    lib_dir: libs
---

```{r setup, include = FALSE}
# Prettify slide appearance
knitr::opts_chunk$set(
  warning = FALSE, 
  message = FALSE,
  fig.height = 6, 
  out.width = "100%", 
  comment = " ",
  dpi = 300
)
xaringanExtra::use_panelset()

# Load packages
library(conflicted)
library(here)
library(tidyverse)
conflict_prefer("filter", "dplyr")
library(gghighlight)

# Import & process data
midwest <- c(
  "Illinois", "Indiana", "Iowa", "Kansas", "Michigan", "Minnesota", "Missouri", 
  "Nebraska", "North Dakota", "Ohio", "South Dakota", "Wisconsin"
)
fatal_crash_smry_by_state <- read_csv(
  here("data", "usa-fatal-crash-totals-2018.csv")
) %>%
  filter(state %in% midwest)

fatal_crash_monthly_counts <- read_csv(
  here("data", "usa-fatal-crash-count-by-month.csv")
) %>%
  rename(crash_year = Crash_Year) %>%
  pivot_longer(
    -crash_year, names_to = "crash_month", values_to = "fatal_crash_freq"
  )

# Source flipbook functions
source("https://raw.githubusercontent.com/EvaMaeRey/little_flipbooks_library/master/xaringan_reveal_parentheses_balanced.R")
```

layout: false
class: bg-main3 split-30 hide-slide-number

.column[

]

.column.slide-in-right[.content.vmiddle[

.sliderbox.shade_main.pad1[
.font5[gghighlight]
]

]]

---

class: middle center bg-main1

.font5[Example 1]

---

```{r gghigh-demo1, eval = FALSE, echo = FALSE}
ggplot(fatal_crash_smry_by_state) +
  aes(x = deaths_per_100m_vmt, y = state) +
  geom_point() + 
  aes(
    y = fct_reorder(
      state, deaths_per_100m_vmt
    )
  ) + 
  geom_segment(
    aes(
      x = 0, y = state, 
      xend = deaths_per_100m_vmt, yend = state
    )
  ) + 
  labs(
    x = paste(
      "Deaths per 100 million", 
      "vehicle miles traveled"
    )
  ) +
  labs(y = "Midwestern state") +
  labs(
    title = paste(
      "Motor vehicle crash death rate",
      "per midwestern state, 2018"
    )
  ) +
  labs(caption = "Data source: IIHS") +
  gghighlight(state %in% c("Iowa", "Ohio"))
```

`r apply_reveal("gghigh-demo1")`

---

class: middle center bg-main1

.font5[Example 2]

---

```{r gghigh-demo2, eval = FALSE, echo = FALSE}
ggplot(fatal_crash_monthly_counts) + 
  aes(x = crash_month, y = fatal_crash_freq) + 
  aes(group = crash_year) +
  geom_line() + 
  scale_x_discrete(limits = month.abb) + 
  aes(color = factor(crash_year)) + 
  labs(x = "Crash month") +
  labs(y = "Fatal crash frequency") +
  labs(color = "Crash year") + 
  labs(
    title = paste(
      "Motor vehicle fatal crash trend",
      "by month, 2010–2019"
    )
  ) +
  labs(caption = "Data source: FARS") +
  gghighlight(max(fatal_crash_freq) > 3000)
```

`r apply_reveal("gghigh-demo2")`

---











